<a href="https://colab.research.google.com/github/HeyWinTomsy/NM/blob/main/%D0%9B%D0%A04_%D0%90%D0%BD%D1%82%D1%80%D0%BE%D0%BF%D0%BE%D0%B2_%D0%9D%D0%B0%D0%B7%D0%B0%D1%80_2_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Я був на парі

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [9]:
matrix = np.random.randint(1,6, size=(3,3))
matrix

array([[5, 2, 1],
       [4, 3, 4],
       [3, 2, 3]])

In [10]:
det = np.linalg.det(matrix)
det

np.float64(4.000000000000001)

In [11]:
product=np.prod(matrix)
product

np.int64(8640)

In [18]:
prod1=np.prod(matrix[0])
prod2=np.prod(matrix[1])
prod3=np.prod(matrix[2])
prod1*prod2*prod3

np.int64(8640)

In [19]:
sum1=np.sum(matrix)
sum1

np.int64(27)

In [20]:
np.max(matrix)

np.int64(5)

In [21]:
np.min(matrix)

np.int64(1)

In [31]:
np.mean(matrix)

np.float64(3.0)

In [32]:
sqrt_matrix=np.sqrt(matrix)
sqrt_matrix

array([[2.23606798, 1.41421356, 1.        ],
       [2.        , 1.73205081, 2.        ],
       [1.73205081, 1.41421356, 1.73205081]])

In [34]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)
row_sums

array([[ 8],
       [11],
       [ 8]])

In [35]:
vector=np.random.randint(1,10,size=25)

vector

array([6, 7, 3, 7, 5, 2, 9, 5, 3, 8, 6, 4, 3, 6, 4, 4, 1, 6, 4, 4, 4, 2,
       7, 6, 5])

In [55]:
sorted_vector =np.sort(vector)[::-1]
sorted_vector

array([9, 8, 7, 7, 7, 6, 6, 6, 6, 6, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3,
       2, 2, 1])

In [56]:
from scipy import stats
mod=stats.mode(vector)
median=np.median(vector)
print(mod)
print(median)

ModeResult(mode=np.int64(4), count=np.int64(6))
5.0


In [57]:
a = np.array([[2, -1, 1], [3, 2, 2], [1, -2, 1]])
b = np.array([2, -2, 1])

x = np.linalg.solve(a, b)
print('Вбудована функція', x.round(1))

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1.round(1))

Вбудована функція [ 2. -1. -3.]
Матричний метод [ 2. -1. -3.]


In [58]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(2.0), np.float64(-1.0), np.float64(-3.0)]
